### ISSUE TITLE
Thank you!... And of course I want something.

### ISSUE THREAD

**Issue by loganpowell** [udamir/allof-merge#142]
👋 @udamir,

First off, this is fantastic. I was pulling (what's left of) my hair out trying to roll this on my own until I found this, which fits the bill perfectly, so thank you!

Question: is there a way to set a rule so that only the `required` fields of a schema object are included in the output?

**Comment by udamir** [comment]
Thank you for your feedback! allof-merge tool has no functionality to filter fields, but you can use [json-crawl]( https://github.com/udamir/json-crawl) to do it.

**Comment by loganpowell** [comment]
Thank you sir
