### ISSUE TITLE
Seems to get stuck in infinite loop on bitbucket openAPI spec

### ISSUE THREAD

**Issue by ryanackley** [udamir/allof-merge#67]
Tried using it on 

https://dac-static.atlassian.com/cloud/bitbucket/swagger.v3.json?_v=2.300.14-0.1297.0

My general workflow is 

```javascript
let api = await SwaggerParser.bundle(url)
api = await SwaggerParser.dereference(api)
api = merge(api, {onMergeError, rules: openApiMergeRules("3.0.x")});
```
`merge` never returns. It's still running after several minutes.

**Comment by udamir** [comment]
Hi! Have you tried to merge before dereference? allof-merge is not supporting cycle references converted to JavaScript object references.

**Comment by udamir** [comment]
Cycle references in input is now supported
